-- CREACIÓN DE VISTAS MATERIALIZADAS

---------------------------
-- 0. Variables de contexto
---------------------------

-- WAREHOUSE
USE WAREHOUSE WH_PROCOLOMBIA_ANALITICA;

-- DATABASE
USE DATABASE REPOSITORIO_TURISMO;

---------------
-- 1. Geografía
---------------
CREATE OR REPLACE VIEW VISTAS.GEOGRAFIA AS
SELECT DISTINCT PAISES.M49_CODE,
    PAISES.ISO_ALPHA2_CODE,
    PAISES.ISO_ALPHA3_CODE,
    PAISES.COUNTRY_OR_AREA,
    CONTINENETES.REGION_NAME,
    MIGRACION.CODIGO_PAIS_MIGRACION,
    MIGRACION.NOMBRE_PAIS_MIGRACION,
    MIGRACION.REGION_NAME_TURISMO,
    MIGRACION.REGION_NAME_TURISMO_AGREGADA,
    MIGRACION.HUB_NAME_TURISMO,
    GLOBALDATA.NOMBRE_GLOBAL_DATA,
    OAG.NOMBRE_OAG,
    CREDIBANCO.NOMBRE_CREDIBANCO,
    IATAGAP.NOMBRE_IATA_GAP,
    REGIONES.SUB_REGION_NAME,
    FORWARDKEYS.COUNTRYCODE AS COUNTRYCODE_FORWARDKEYS
FROM CORRELATIVAS.PAISES AS PAISES
    LEFT JOIN CORRELATIVAS.CONTINENTES AS CONTINENETES ON PAISES.REGION_CODE = CONTINENETES.REGION_CODE
    LEFT JOIN CORRELATIVAS.PAISES_MIGRACION AS MIGRACION ON PAISES.M49_CODE = MIGRACION.M49_CODE
    LEFT JOIN CORRELATIVAS.PAISES_GLOBALDATA AS GLOBALDATA ON PAISES.M49_CODE = GLOBALDATA.M49_CODE
    LEFT JOIN CORRELATIVAS.PAISES_OAG AS OAG ON PAISES.M49_CODE = OAG.M49_CODE
    LEFT JOIN CORRELATIVAS.PAISES_CREDIBANCO AS CREDIBANCO ON PAISES.M49_CODE = CREDIBANCO.M49_CODE
    LEFT JOIN CORRELATIVAS.PAISES_IATAGAP AS IATAGAP ON PAISES.M49_CODE = IATAGAP.M49_CODE
    LEFT JOIN CORRELATIVAS.REGIONES AS REGIONES ON PAISES.SUB_REGION_CODE = REGIONES.SUB_REGION_CODE
    LEFT JOIN (SELECT DISTINCT COUNTRYCODE, M49_CODE FROM CORRELATIVAS.PAISES_FORWARDKEYS) AS FORWARDKEYS ON PAISES.M49_CODE = FORWARDKEYS.M49_CODE;

----------------
-- 2. GlobalData
----------------

-- Flujos de viajeros hacia el mundo

CREATE OR REPLACE VIEW VISTAS.GLOBALDATA_VIAJEROS_MUNDO AS
SELECT 
    VIAJEROS_MUNDO.COUNTRY AS PAIS_GLOBALDATA,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS,
    -- Traducción de los valores de la columna SUB_INDICATORS_1 (MEDIO) a español
    CASE 
        WHEN VIAJEROS_MUNDO.SUB_INDICATORS_1 = 'Land' THEN 'Tierra'
        WHEN VIAJEROS_MUNDO.SUB_INDICATORS_1 = 'Rail' THEN 'Tren'
        WHEN VIAJEROS_MUNDO.SUB_INDICATORS_1 = 'Air' THEN 'Aéreo'
        WHEN VIAJEROS_MUNDO.SUB_INDICATORS_1 = 'Sea' THEN 'Marítimo'
        ELSE 'Desconocido'
    END AS MEDIO,
    VIAJEROS_MUNDO.YEAR AS YEAR,
    CAST(SUM(VIAJEROS_MUNDO.VALUE) AS BIGINT) AS VIAJEROS
FROM GLOBALDATA.FLUJO_VIAJEROS_MUNDO AS VIAJEROS_MUNDO
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA ON VIAJEROS_MUNDO.COUNTRY = GEOGRAFIA.NOMBRE_GLOBAL_DATA
GROUP BY 
    VIAJEROS_MUNDO.COUNTRY, 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    VIAJEROS_MUNDO.SUB_INDICATORS_1, 
    VIAJEROS_MUNDO.YEAR
ORDER BY 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    VIAJEROS_MUNDO.YEAR ASC;


-- Noches de percnotación promedio

CREATE OR REPLACE VIEW VISTAS.GLOBALDATA_NOCHES_PROMEDIO AS
SELECT NOCHES_PROMEDIO.COUNTRY AS PAIS_GLOBALDATA,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS,
    NOCHES_PROMEDIO.YEAR_COPY AS YEAR,
    CAST(SUM(NOCHES_PROMEDIO.AVERAGE_LENGTH_OF_TRIP_BY_TYPE_DAYS) AS BIGINT) AS NOCHES
FROM GLOBALDATA.NOCHES_PROMEDIO AS NOCHES_PROMEDIO
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA ON NOCHES_PROMEDIO.COUNTRY = GEOGRAFIA.NOMBRE_GLOBAL_DATA
GROUP BY NOCHES_PROMEDIO.COUNTRY, GEOGRAFIA.COUNTRY_OR_AREA, NOCHES_PROMEDIO.YEAR_COPY
ORDER BY GEOGRAFIA.COUNTRY_OR_AREA, NOCHES_PROMEDIO.YEAR_COPY ASC;


-- Gasto promedio del viajero al mundo - Principales categorías de gasto

CREATE OR REPLACE VIEW VISTAS.GLOBALDATA_CATEGORIAS_GASTO AS
SELECT 
    CATEGORIAS_GASTO.COUNTRY AS PAIS_GLOBALDATA,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS,
    CATEGORIAS_GASTO.YEAR AS YEAR,
    -- Traducción de los valores de la columna _SECTOR_ (CATEGORIA_GASTO) a español
    CASE 
        WHEN CATEGORIAS_GASTO._SECTOR_ = 'Transportation' THEN 'Transporte'
        WHEN CATEGORIAS_GASTO._SECTOR_ = 'Travel Intermediation' THEN 'Intermediación de viajes'
        WHEN CATEGORIAS_GASTO._SECTOR_ = 'Retail' THEN 'Comercio minorista'
        WHEN CATEGORIAS_GASTO._SECTOR_ = 'Entertainment & Sightseeing' THEN 'Entretenimiento y turismo'
        WHEN CATEGORIAS_GASTO._SECTOR_ = 'Foodservice' THEN 'Servicios de alimentación'
        WHEN CATEGORIAS_GASTO._SECTOR_ = 'Other Sectors' THEN 'Otros sectores'
        WHEN CATEGORIAS_GASTO._SECTOR_ = 'Accommodation' THEN 'Alojamiento'
        ELSE 'Sin clasificar'
    END AS CATEGORIA_GASTO,
    CAST(SUM(CATEGORIAS_GASTO.VALUE_1) AS BIGINT) AS GASTO
FROM GLOBALDATA.CATEGORIAS_GASTO AS CATEGORIAS_GASTO
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA ON CATEGORIAS_GASTO.COUNTRY = GEOGRAFIA.NOMBRE_GLOBAL_DATA
GROUP BY 
    CATEGORIAS_GASTO.COUNTRY, 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    CATEGORIAS_GASTO.YEAR, 
    CATEGORIAS_GASTO._SECTOR_
ORDER BY 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    CATEGORIAS_GASTO.YEAR ASC;

-- Rango de edad del viajero promedio

CREATE OR REPLACE VIEW VISTAS.GLOBALDATA_RANGO_EDAD AS
SELECT 
    RANGO_EDAD.COUNTRY AS PAIS_GLOBALDATA,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS,
    RANGO_EDAD.YEAR AS YEAR,
    -- Traducción de los valores de la columna SUB_INDICATORS_1 (RANGO_EDAD) a español
    CASE 
        WHEN RANGO_EDAD.SUB_INDICATORS_1 = '0-14' THEN '0-14 años'
        WHEN RANGO_EDAD.SUB_INDICATORS_1 = '15-24' THEN '15-24 años'
        WHEN RANGO_EDAD.SUB_INDICATORS_1 = '25-34' THEN '25-34 años'
        WHEN RANGO_EDAD.SUB_INDICATORS_1 = '35-49' THEN '35-49 años'
        WHEN RANGO_EDAD.SUB_INDICATORS_1 = '50-64' THEN '50-64 años'
        WHEN RANGO_EDAD.SUB_INDICATORS_1 = 'Over 65' THEN 'Más de 65 años'
        ELSE 'Rango desconocido'
    END AS RANGO_EDAD,
    CAST(SUM(RANGO_EDAD.VALUE) AS BIGINT) AS VIAJEROS
FROM GLOBALDATA.RANGO_EDAD AS RANGO_EDAD
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA ON RANGO_EDAD.COUNTRY = GEOGRAFIA.NOMBRE_GLOBAL_DATA
GROUP BY 
    RANGO_EDAD.COUNTRY, 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    RANGO_EDAD.YEAR, 
    RANGO_EDAD.SUB_INDICATORS_1
ORDER BY 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    RANGO_EDAD.YEAR ASC;


-- Motivo de viaje
CREATE OR REPLACE VIEW VISTAS.GLOBALDATA_MOTIVO_VIAJE AS
SELECT 
    MOTIVO_VIAJE.COUNTRY AS PAIS_GLOBALDATA,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS,
    MOTIVO_VIAJE.YEAR AS YEAR,
    -- Traducción de los valores de la columna PURPOSE (MOTIVO_VIAJE) a español
    CASE 
        WHEN MOTIVO_VIAJE.PURPOSE = 'Other Personal' THEN 'Otro personal'
        WHEN MOTIVO_VIAJE.PURPOSE = 'Business' THEN 'Negocios'
        WHEN MOTIVO_VIAJE.PURPOSE = 'Leisure' THEN 'Ocio'
        WHEN MOTIVO_VIAJE.PURPOSE = 'VFR' THEN 'Visitar familiares o amigos'
        ELSE 'Motivo desconocido'
    END AS MOTIVO_VIAJE,
    CAST(SUM(MOTIVO_VIAJE.VALUE) AS BIGINT) AS VIAJEROS
FROM GLOBALDATA.MOTIVO_VIAJE AS MOTIVO_VIAJE
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA ON MOTIVO_VIAJE.COUNTRY = GEOGRAFIA.NOMBRE_GLOBAL_DATA
GROUP BY 
    MOTIVO_VIAJE.COUNTRY, 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    MOTIVO_VIAJE.YEAR, 
    MOTIVO_VIAJE.PURPOSE
ORDER BY 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    MOTIVO_VIAJE.YEAR ASC;

-- Forma de viaje (solos, pareja, grupos, en familia)
CREATE OR REPLACE VIEW VISTAS.GLOBALDATA_FORMA_VIAJE AS
SELECT 
    FORMA_VIAJE.COUNTRY AS PAIS_GLOBALDATA,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS,
    FORMA_VIAJE.YEAR AS YEAR,
    -- Traducción de los valores de la columna SUB_INDICATORS_1 (FORMA_VIAJE) a español
    CASE 
        WHEN FORMA_VIAJE.SUB_INDICATORS_1 = 'Singles' THEN 'Solteros'
        WHEN FORMA_VIAJE.SUB_INDICATORS_1 = 'Couples' THEN 'Parejas'
        WHEN FORMA_VIAJE.SUB_INDICATORS_1 = 'Families' THEN 'Familias'
        WHEN FORMA_VIAJE.SUB_INDICATORS_1 = 'Group' THEN 'Grupo'
        ELSE 'Forma desconocida'
    END AS FORMA_VIAJE,
    CAST(SUM(FORMA_VIAJE.VALUE) AS BIGINT) AS VIAJEROS
FROM GLOBALDATA.FORMA_VIAJE AS FORMA_VIAJE
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA ON FORMA_VIAJE.COUNTRY = GEOGRAFIA.NOMBRE_GLOBAL_DATA
GROUP BY 
    FORMA_VIAJE.COUNTRY, 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    FORMA_VIAJE.YEAR, 
    FORMA_VIAJE.SUB_INDICATORS_1
ORDER BY 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    FORMA_VIAJE.YEAR ASC;

-- Principales destinos internacionales -- Flujos de viajeros a la región

CREATE OR REPLACE VIEW VISTAS.GLOBALDATA_FLUJOS_VIAJEROS_REGION AS
SELECT VIAJEROS_REGION.COUNTRY AS PAIS_GLOBALDATA_ORIGEN,
    GEOGRAFIA_ORIGEN.COUNTRY_OR_AREA AS PAIS_ORIGEN,
    VIAJEROS_REGION.COUNTRY_OF_ORIGIN_DESTINATION AS PAIS_GLOBALDATA_DESTINO,
    GEOGRAFIA_DESTINO.COUNTRY_OR_AREA AS PAIS_DESTINO,
    VIAJEROS_REGION.YEAR AS YEAR,
    CAST(VIAJEROS_REGION.VALUE AS BIGINT) AS VIAJEROS
FROM GLOBALDATA.FLUJO_VIAJEROS_REGION AS VIAJEROS_REGION
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA_ORIGEN ON VIAJEROS_REGION.COUNTRY = GEOGRAFIA_ORIGEN.NOMBRE_GLOBAL_DATA
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA_DESTINO ON VIAJEROS_REGION.COUNTRY_OF_ORIGIN_DESTINATION = GEOGRAFIA_DESTINO.NOMBRE_GLOBAL_DATA;


-- Flujos internacionales por motivo de negocios

CREATE OR REPLACE VIEW VISTAS.GLOBALDATA_MICE AS
SELECT 
    MICE.COUNTRY AS PAIS_GLOBALDATA,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS,
    MICE.YEAR AS YEAR,
    -- Traducción de los valores de la columna SUB_INDICATORS_1 (MOTIVO_VIAJE) a español
    CASE 
        WHEN MICE.SUB_INDICATORS_1 = 'Other Business Travel' THEN 'Otros viajes de negocios'
        WHEN MICE.SUB_INDICATORS_1 = 'MICE' THEN 'Reuniones, incentivos, congresos y exposiciones (MICE)'
        ELSE 'Motivo desconocido'
    END AS MOTIVO_VIAJE,
    CAST(SUM(MICE.VALUE) AS BIGINT) AS VIAJEROS
FROM GLOBALDATA.FLUJO_MICE AS MICE
    LEFT JOIN (SELECT DISTINCT NOMBRE_GLOBAL_DATA, COUNTRY_OR_AREA FROM VISTAS.GEOGRAFIA) AS GEOGRAFIA ON MICE.COUNTRY = GEOGRAFIA.NOMBRE_GLOBAL_DATA
GROUP BY 
    MICE.COUNTRY, 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    MICE.YEAR, 
    MICE.SUB_INDICATORS_1
ORDER BY 
    GEOGRAFIA.COUNTRY_OR_AREA, 
    MICE.YEAR ASC;

---------
-- 3. OAG
---------

-- Conectividad del país con el mundo
CREATE OR REPLACE VIEW VISTAS.OAG_CONECTIVIDAD_MUNDO AS
SELECT OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_CODE,
    OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_NAME,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA AS PAIS_DEPARTURE,
    OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE,
    OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_NAME,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA AS PAIS_ARRIVAL,
    OAG_CONECTIVIDAD_MUNDO.TIME_SERIES,
    CAST(SUM(OAG_CONECTIVIDAD_MUNDO.FREQUENCY) AS BIGINT) AS FRECUENCIAS,
    CAST(SUM(OAG_CONECTIVIDAD_MUNDO.SEATS_TOTAL) AS BIGINT) AS SILLAS
FROM OAG.CONECTIVIDAD_DIRECTA AS OAG_CONECTIVIDAD_MUNDO
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_DEP ON OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_CODE = GEOGRAFIA_DEP.COUNTRYCODE_FORWARDKEYS
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_ARR ON OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE = GEOGRAFIA_ARR.COUNTRYCODE_FORWARDKEYS
GROUP BY OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_CODE, 
    OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_NAME, 
    GEOGRAFIA_DEP.COUNTRY_OR_AREA, 
    OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE, 
    OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_NAME, 
    GEOGRAFIA_ARR.COUNTRY_OR_AREA,
    OAG_CONECTIVIDAD_MUNDO.TIME_SERIES
ORDER BY GEOGRAFIA_DEP.COUNTRY_OR_AREA, GEOGRAFIA_ARR.COUNTRY_OR_AREA, OAG_CONECTIVIDAD_MUNDO.TIME_SERIES ASC;


-- Conectividad aérea hacia Colombia
CREATE OR REPLACE VIEW VISTAS.OAG_CONECTIVIDAD_COLOMBIA AS
SELECT OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_CODE,
    OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_NAME,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA AS PAIS_DEPARTURE,
    OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE,
    OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_NAME,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA AS PAIS_ARRIVAL,
    OAG_CONECTIVIDAD_MUNDO.ARR_CITY_CODE,
    OAG_CONECTIVIDAD_MUNDO.ARR_CITY_NAME,
    AEROPUERTOS.COD_DANE_MUNICIPIO,
	AEROPUERTOS.MUNICIPIO_DANE,
	AEROPUERTOS.COD_DANE_DEPARTAMENTO,
	AEROPUERTOS.DEPARTAMENTO_DANE,
    OAG_CONECTIVIDAD_MUNDO.TIME_SERIES,
    CAST(SUM(OAG_CONECTIVIDAD_MUNDO.FREQUENCY) AS BIGINT) AS FRECUENCIAS,
    CAST(SUM(OAG_CONECTIVIDAD_MUNDO.SEATS_TOTAL) AS BIGINT) AS SILLAS
FROM OAG.CONECTIVIDAD_DIRECTA AS OAG_CONECTIVIDAD_MUNDO
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_DEP ON OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_CODE = GEOGRAFIA_DEP.COUNTRYCODE_FORWARDKEYS
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_ARR ON OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE = GEOGRAFIA_ARR.COUNTRYCODE_FORWARDKEYS
    LEFT JOIN CORRELATIVAS.DIVIPOLA_AEROPUERTOS AS AEROPUERTOS ON OAG_CONECTIVIDAD_MUNDO.ARR_CITY_CODE = AEROPUERTOS.ARR_CITY_CODE
WHERE GEOGRAFIA_ARR.COUNTRY_OR_AREA = 'Colombia'
GROUP BY OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_CODE, 
    OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_NAME, 
    GEOGRAFIA_DEP.COUNTRY_OR_AREA, 
    OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE, 
    OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_NAME, 
    GEOGRAFIA_ARR.COUNTRY_OR_AREA,
    OAG_CONECTIVIDAD_MUNDO.ARR_CITY_CODE,
    OAG_CONECTIVIDAD_MUNDO.ARR_CITY_NAME,
    AEROPUERTOS.COD_DANE_MUNICIPIO,
	AEROPUERTOS.MUNICIPIO_DANE,
	AEROPUERTOS.COD_DANE_DEPARTAMENTO,
	AEROPUERTOS.DEPARTAMENTO_DANE,
    OAG_CONECTIVIDAD_MUNDO.TIME_SERIES
ORDER BY GEOGRAFIA_DEP.COUNTRY_OR_AREA, GEOGRAFIA_ARR.COUNTRY_OR_AREA, OAG_CONECTIVIDAD_MUNDO.TIME_SERIES ASC;

-----------------
-- 4. ForwardKeys
-----------------

-- Reservas aéreas activas del país hacia México, Costa Rica, Perú y Chile -- Reservas aéreas activas del país hacia Colombia

CREATE OR REPLACE VIEW VISTAS.FORWARDKEYS_RESERVAS_PAISES AS
SELECT 
    FORWARDKEYS_RESERVAS_PAISES.TRIP_ORIGIN_COUNTRY,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA AS PAIS_DEPARTURE,
    FORWARDKEYS_RESERVAS_PAISES.FLIGHT_LEG_DESTINATION_COUNTRY,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA AS PAIS_ARRIVAL,
    FORWARDKEYS_RESERVAS_PAISES.FLIGHT_LEG_ARRIVAL_DATE,
    FORWARDKEYS_RESERVAS_PAISES.LOS_AT_DESTINATION_CAT,
    FORWARDKEYS_RESERVAS_PAISES.LOS_AT_DESTINATION_NIGHTS,
    -- Traducción de TRIP_CABIN_CLASS al español
    CASE 
        WHEN FORWARDKEYS_RESERVAS_PAISES.TRIP_CABIN_CLASS = 'PREMIUM_ECONOMY' THEN 'Economía Premium'
        WHEN FORWARDKEYS_RESERVAS_PAISES.TRIP_CABIN_CLASS = 'ECONOMY' THEN 'Económica'
        WHEN FORWARDKEYS_RESERVAS_PAISES.TRIP_CABIN_CLASS = 'FIRST' THEN 'Primera Clase'
        WHEN FORWARDKEYS_RESERVAS_PAISES.TRIP_CABIN_CLASS = 'BUSINESS' THEN 'Negocios'
        ELSE 'Clase Desconocida'
    END AS CLASE_CABINA,
    -- Traducción de PAX_PROFILE al español
    CASE 
        WHEN FORWARDKEYS_RESERVAS_PAISES.PAX_PROFILE = 'LEISURE' THEN 'Ocio'
        WHEN FORWARDKEYS_RESERVAS_PAISES.PAX_PROFILE = 'BUSINESS' THEN 'Negocios'
        WHEN FORWARDKEYS_RESERVAS_PAISES.PAX_PROFILE = 'GROUP' THEN 'Grupo'
        WHEN FORWARDKEYS_RESERVAS_PAISES.PAX_PROFILE = 'VFR' THEN 'Visitar Familiares o Amigos'
        ELSE 'Perfil Desconocido'
    END AS PERFIL_PASAJERO,
    CAST(SUM(FORWARDKEYS_RESERVAS_PAISES.PAX) AS BIGINT) AS RESERVAS
FROM FORWARDKEYS.RESERVAS AS FORWARDKEYS_RESERVAS_PAISES
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_DEP ON FORWARDKEYS_RESERVAS_PAISES.TRIP_ORIGIN_COUNTRY = GEOGRAFIA_DEP.COUNTRYCODE_FORWARDKEYS
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_ARR ON FORWARDKEYS_RESERVAS_PAISES.FLIGHT_LEG_DESTINATION_COUNTRY = GEOGRAFIA_ARR.COUNTRYCODE_FORWARDKEYS
WHERE FORWARDKEYS_RESERVAS_PAISES.FLIGHT_LEG_DESTINATION_COUNTRY IN ('MX', 'CL', 'PE', 'CR', 'CO')
GROUP BY 
    FORWARDKEYS_RESERVAS_PAISES.TRIP_ORIGIN_COUNTRY,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA,
    FORWARDKEYS_RESERVAS_PAISES.FLIGHT_LEG_DESTINATION_COUNTRY,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA,
    FORWARDKEYS_RESERVAS_PAISES.FLIGHT_LEG_ARRIVAL_DATE,
    FORWARDKEYS_RESERVAS_PAISES.LOS_AT_DESTINATION_CAT,
    FORWARDKEYS_RESERVAS_PAISES.LOS_AT_DESTINATION_NIGHTS,
    FORWARDKEYS_RESERVAS_PAISES.TRIP_CABIN_CLASS,
    FORWARDKEYS_RESERVAS_PAISES.PAX_PROFILE
ORDER BY 
    FORWARDKEYS_RESERVAS_PAISES.TRIP_ORIGIN_COUNTRY,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA,
    FORWARDKEYS_RESERVAS_PAISES.FLIGHT_LEG_DESTINATION_COUNTRY,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA,
    FORWARDKEYS_RESERVAS_PAISES.FLIGHT_LEG_ARRIVAL_DATE,
    FORWARDKEYS_RESERVAS_PAISES.LOS_AT_DESTINATION_CAT,
    FORWARDKEYS_RESERVAS_PAISES.LOS_AT_DESTINATION_NIGHTS,
    FORWARDKEYS_RESERVAS_PAISES.TRIP_CABIN_CLASS,
    FORWARDKEYS_RESERVAS_PAISES.PAX_PROFILE ASC;


-- Búsquedas aéreas del país hacia México, Costa Rica, Perú y Chile - Búsquedas aéreas del país hacia Colombia
CREATE OR REPLACE VIEW VISTAS.FORWARDKEYS_BUSQUEDAS_PAISES AS
SELECT FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_ORIGIN_COUNTRY,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA AS PAIS_DEPARTURE,
    FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_DESTINATION_COUNTRY,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA AS PAIS_ARRIVAL,
    FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_DATE,
    CAST(SUM(FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_PAX) AS BIGINT) AS BUSQUEDAS
FROM FORWARDKEYS.BUSQUEDAS AS FORWARDKEYS_BUSQUEDAS_PAISES
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_DEP ON FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_ORIGIN_COUNTRY = GEOGRAFIA_DEP.COUNTRYCODE_FORWARDKEYS
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_ARR ON FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_DESTINATION_COUNTRY = GEOGRAFIA_ARR.COUNTRYCODE_FORWARDKEYS
WHERE FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_DESTINATION_COUNTRY IN ('MX', 'CL', 'PE', 'CR', 'CO')
GROUP BY FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_ORIGIN_COUNTRY,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA,
    FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_DESTINATION_COUNTRY,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA,
    FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_DATE
ORDER BY FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_ORIGIN_COUNTRY,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA,
    FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_DESTINATION_COUNTRY,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA,
    FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_DATE ASC;


----------------
-- 5. Credibanco
----------------

-- Gasto con tarjeta de crédito proveniente de ese país en Colombia
CREATE OR REPLACE VIEW VISTAS.CREDIBANCO_GASTO AS
SELECT 
    CREDIBANCO_GASTO.ANIO,
    CREDIBANCO_GASTO.MES,
    CREDIBANCO_GASTO.PAIS_ORIGEN,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS,
    INITCAP(CREDIBANCO_GASTO.CATEGORIA) AS CATEGORIA,
    -- Aplicar el CASE para formatear CLASIFICACION_CATEGORIA
    CASE 
        WHEN CREDIBANCO_GASTO.CLASIFICACION_CATEGORIA = 'OTROS' THEN 'Otros'
        WHEN CREDIBANCO_GASTO.CLASIFICACION_CATEGORIA = 'INDIRECTO' THEN 'Indirecto'
        WHEN CREDIBANCO_GASTO.CLASIFICACION_CATEGORIA = 'DIRECTO' THEN 'Directo'
        ELSE CREDIBANCO_GASTO.CLASIFICACION_CATEGORIA
    END AS CLASIFICACION_CATEGORIA_FORMATADA,
    CAST(SUM(CREDIBANCO_GASTO.FACTURACION_COP) AS BIGINT) AS FACTURACION_COP,
    CAST(SUM(CREDIBANCO_GASTO.FACTURACION_USD) AS BIGINT) AS FACTURACION_USD,
    CAST(SUM(CREDIBANCO_GASTO.TURISTAS) AS BIGINT) AS TURISTAS,
    CAST(SUM(CREDIBANCO_GASTO.TRANSACCIONES) AS BIGINT) AS TRANSACCIONES
FROM CREDIBANCO.GASTO AS CREDIBANCO_GASTO 
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA ON CREDIBANCO_GASTO.PAIS_ORIGEN = GEOGRAFIA.NOMBRE_CREDIBANCO
GROUP BY 
    CREDIBANCO_GASTO.ANIO,
    CREDIBANCO_GASTO.MES,
    CREDIBANCO_GASTO.PAIS_ORIGEN,
    GEOGRAFIA.COUNTRY_OR_AREA,
    CREDIBANCO_GASTO.CATEGORIA,
    CREDIBANCO_GASTO.CLASIFICACION_CATEGORIA
ORDER BY 
    CREDIBANCO_GASTO.ANIO,
    CREDIBANCO_GASTO.MES,
    CREDIBANCO_GASTO.PAIS_ORIGEN,
    GEOGRAFIA.COUNTRY_OR_AREA,
    CREDIBANCO_GASTO.CATEGORIA,
    CREDIBANCO_GASTO.CLASIFICACION_CATEGORIA ASC;

--------------
-- 6. IATA-GAP
--------------

-- Indicadores de agencias de ese mercado que venden Colombia como destino - Agencias
CREATE OR REPLACE VIEW VISTAS.IATAGAP_AGENCIAS AS
SELECT DISTINCT IATAGAP_AGENCIAS.TRAVEL_AGENCY_NAME AS AGENCIAS,
    IATAGAP_AGENCIAS.TRAVEL_AGENCY_COUNTRY,
    GEOGRAFIA_AGENCIA.COUNTRY_OR_AREA AS PAIS_AGENCIA,
    IATAGAP_AGENCIAS.TRAVEL_AGENCY_CITY,
    IATAGAP_AGENCIAS.YEAR AS YEAR,
    SUBSTR(IATAGAP_AGENCIAS.YEAR, 1, 4) AS YY
FROM IATAGAP.AGENCIAS AS IATAGAP_AGENCIAS
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_AGENCIA ON IATAGAP_AGENCIAS.TRAVEL_AGENCY_COUNTRY = GEOGRAFIA_AGENCIA.NOMBRE_IATA_GAP
WHERE 
    IATAGAP_AGENCIAS.VALUE > 0
    AND 
    IATAGAP_AGENCIAS.TRIP_DESTINATION_COUNTRY = 'Colombia';