-- CREACIÓN DE VISTAS MATERIALIZADAS

---------------------------
-- 1. Variables de contexto
---------------------------

-- WAREHOUSE
USE WAREHOUSE WH_PROCOLOMBIA_ANALITICA;

-- DATABASE
USE DATABASE REPOSITORIO_TURISMO;

----------------
-- 2. GlobalData
----------------

-- Verificación de completitud de países

SELECT DISTINCT PAISES.COUNTRY AS PAIS_GLOBALDATA,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS
FROM (
    SELECT DISTINCT VIAJEROS_MUNDO.COUNTRY AS COUNTRY
    FROM GLOBALDATA.FLUJO_VIAJEROS_MUNDO AS VIAJEROS_MUNDO

    UNION ALL

    SELECT DISTINCT NOCHES_PROMEDIO.COUNTRY AS COUNTRY
    FROM GLOBALDATA.NOCHES_PROMEDIO AS NOCHES_PROMEDIO

    UNION ALL

    SELECT DISTINCT CATEGORIAS_GASTO.COUNTRY AS COUNTRY
    FROM GLOBALDATA.CATEGORIAS_GASTO AS CATEGORIAS_GASTO

    UNION ALL

    SELECT DISTINCT RANGO_EDAD.COUNTRY AS COUNTRY
    FROM GLOBALDATA.RANGO_EDAD AS RANGO_EDAD

    UNION ALL

    SELECT DISTINCT MOTIVO_VIAJE.COUNTRY AS COUNTRY
    FROM GLOBALDATA.MOTIVO_VIAJE AS MOTIVO_VIAJE

    UNION ALL

    SELECT DISTINCT FORMA_VIAJE.COUNTRY AS COUNTRY
    FROM GLOBALDATA.FORMA_VIAJE AS FORMA_VIAJE

    UNION ALL

    SELECT DISTINCT VIAJEROS_REGION.COUNTRY AS COUNTRY
    FROM GLOBALDATA.FLUJO_VIAJEROS_REGION AS VIAJEROS_REGION

    UNION ALL

    SELECT DISTINCT VIAJEROS_REGION.COUNTRY_OF_ORIGIN_DESTINATION AS COUNTRY
    FROM GLOBALDATA.FLUJO_VIAJEROS_REGION AS VIAJEROS_REGION

    UNION ALL

    SELECT DISTINCT MICE.COUNTRY AS COUNTRY
    FROM GLOBALDATA.FLUJO_MICE AS MICE
) AS PAISES
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA ON PAISES.COUNTRY = GEOGRAFIA.NOMBRE_GLOBAL_DATA
WHERE GEOGRAFIA.COUNTRY_OR_AREA IS NULL;

---------
-- 3. OAG
---------

-- Verificación de completitud de países

SELECT DISTINCT PAISES.CODIGO,
    PAISES.PAIS
FROM (
    SELECT DISTINCT OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_CODE AS CODIGO,
        GEOGRAFIA_DEP.COUNTRY_OR_AREA AS PAIS
    FROM OAG.CONECTIVIDAD_DIRECTA AS OAG_CONECTIVIDAD_MUNDO
        LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_DEP ON OAG_CONECTIVIDAD_MUNDO.DEP_IATA_COUNTRY_CODE = GEOGRAFIA_DEP.COUNTRYCODE_FORWARDKEYS

    UNION ALL

    SELECT DISTINCT OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE AS CODIGO,
        GEOGRAFIA_ARR.COUNTRY_OR_AREA AS PAIS
    FROM OAG.CONECTIVIDAD_DIRECTA AS OAG_CONECTIVIDAD_MUNDO
        LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_ARR ON OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE = GEOGRAFIA_ARR.COUNTRYCODE_FORWARDKEYS
) AS PAISES
WHERE PAISES.PAIS IS NULL;

-- Verificación de completitud de aeropuertos (CIUDAD DE LLEGADA EN COLOMBIA)
SELECT DISTINCT OAG_CONECTIVIDAD_MUNDO.ARR_CITY_CODE,
    OAG_CONECTIVIDAD_MUNDO.ARR_CITY_NAME,
    AEROPUERTOS.COD_DANE_MUNICIPIO,
	AEROPUERTOS.MUNICIPIO_DANE,
	AEROPUERTOS.COD_DANE_DEPARTAMENTO,
	AEROPUERTOS.DEPARTAMENTO_DANE 
FROM OAG.CONECTIVIDAD_DIRECTA AS OAG_CONECTIVIDAD_MUNDO
    LEFT JOIN CORRELATIVAS.DIVIPOLA_AEROPUERTOS AS AEROPUERTOS ON OAG_CONECTIVIDAD_MUNDO.ARR_CITY_CODE = AEROPUERTOS.ARR_CITY_CODE
WHERE OAG_CONECTIVIDAD_MUNDO.ARR_IATA_COUNTRY_CODE = 'CO'
    AND AEROPUERTOS.COD_DANE_MUNICIPIO IS NULL;

-----------------
-- 4. ForwardKeys
-----------------

-- Verificación de completitud de países
SELECT *
FROM 
    (
SELECT DISTINCT FORWARDKEYS_RESERVAS_PAISES.TRIP_ORIGIN_COUNTRY AS COD,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA AS PAIS
FROM FORWARDKEYS.RESERVAS AS FORWARDKEYS_RESERVAS_PAISES
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_DEP ON FORWARDKEYS_RESERVAS_PAISES.TRIP_ORIGIN_COUNTRY = GEOGRAFIA_DEP.COUNTRYCODE_FORWARDKEYS

UNION ALL

SELECT DISTINCT FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_ORIGIN_COUNTRY AS COD,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA AS PAIS,
FROM FORWARDKEYS.BUSQUEDAS AS FORWARDKEYS_BUSQUEDAS_PAISES
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_DEP ON FORWARDKEYS_BUSQUEDAS_PAISES.SEARCH_ORIGIN_COUNTRY = GEOGRAFIA_DEP.COUNTRYCODE_FORWARDKEYS
    ) AS PAISES
WHERE PAISES.PAIS IS NULL;

----------------
-- 5. Credibanco
----------------

-- Verificación de completitud de países

SELECT DISTINCT CREDIBANCO_GASTO.PAIS_ORIGEN,
    GEOGRAFIA.COUNTRY_OR_AREA AS PAIS
FROM CREDIBANCO.GASTO AS CREDIBANCO_GASTO 
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA ON CREDIBANCO_GASTO.PAIS_ORIGEN = GEOGRAFIA.NOMBRE_CREDIBANCO
WHERE GEOGRAFIA.COUNTRY_OR_AREA IS NULL; 

--------------
-- 6. IATA-GAP
--------------

-- Verificación de completitud de países

SELECT DISTINCT *
FROM 
    (
SELECT IATAGAP_AGENCIAS.TRAVEL_AGENCY_COUNTRY AS COD,
    GEOGRAFIA_AGENCIA.COUNTRY_OR_AREA AS PAIS
FROM IATAGAP.AGENCIAS AS IATAGAP_AGENCIAS
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_AGENCIA ON IATAGAP_AGENCIAS.TRAVEL_AGENCY_COUNTRY = GEOGRAFIA_AGENCIA.NOMBRE_IATA_GAP

UNION ALL

SELECT IATAGAP_AGENCIAS.TRIP_ORIGIN_COUNTRY AS COD,
    GEOGRAFIA_DEP.COUNTRY_OR_AREA AS PAIS
FROM IATAGAP.AGENCIAS AS IATAGAP_AGENCIAS
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_DEP ON IATAGAP_AGENCIAS.TRIP_ORIGIN_COUNTRY = GEOGRAFIA_DEP.NOMBRE_IATA_GAP
    
UNION ALL

SELECT IATAGAP_AGENCIAS.TRIP_DESTINATION_COUNTRY AS COD,
    GEOGRAFIA_ARR.COUNTRY_OR_AREA AS PAIS
FROM IATAGAP.AGENCIAS AS IATAGAP_AGENCIAS
    LEFT JOIN VISTAS.GEOGRAFIA AS GEOGRAFIA_ARR ON IATAGAP_AGENCIAS.TRIP_DESTINATION_COUNTRY = GEOGRAFIA_ARR.NOMBRE_IATA_GAP
    ) AS PAISES
WHERE PAISES.PAIS IS NULL;